producer_module: domains.logistics.shipment_producer

bootstrap_servers: kafka1:9092,kafka2:9092,kafka3:9092
schema_registry_url: http://schema-registry:8081

topic: bronze.logistics.shipments
producer_error_topic: producer-errors.logistics.shipments
schema_path: schemas/logistics_shipment_event.avsc
sleep_seconds: 2