producer_module: domains.logistics.vehicle_producer

bootstrap_servers: kafka1:9092,kafka2:9092,kafka3:9092
schema_registry_url: http://schema-registry:8081

topic: bronze.logistics.vehicles
producer_error_topic: producer-errors.logistics.vehicles
schema_path: schemas/logistics_vehicle_event.avsc
sleep_seconds: 3600