producer_module: domains.logistics.location_producer

bootstrap_servers: kafka1:9092,kafka2:9092,kafka3:9092
schema_registry_url: http://schema-registry:8081

topic: bronze.logistics.locations
producer_error_topic: producer-errors.logistics.locations
schema_path: schemas/logistics_location_event.avsc
sleep_seconds: 86400