name: sales-customers-producer
producer_module: domains.sales.customers_producer

bootstrap_servers: kafka1:9092,kafka2:9092,kafka3:9092
schema_registry_url: http://schema-registry:8081

topic: bronze.sales.customers
producer_error_topic: producer-errors.sales.customers
schema_path: schemas/sales_customer_event.avsc
sleep_seconds: 2