producer_module: domains.sensors.alert_producer

bootstrap_servers: kafka1:9092,kafka2:9092,kafka3:9092
schema_registry_url: http://schema-registry:8081

topic: bronze.sensors.alerts
producer_error_topic: producer-errors.sensors.alerts
schema_path: schemas/sensor_alert_event.avsc
sleep_seconds: 3