producer_module: domains.sensors.machine_producer

bootstrap_servers: kafka1:9092,kafka2:9092,kafka3:9092
schema_registry_url: http://schema-registry:8081

topic: bronze.sensors.machines
producer_error_topic: producer-errors.sensors.machines
schema_path: schemas/sensor_machine_event.avsc
sleep_seconds: 7200